### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DoYup** [mkanai/ldsc-corrplot-rg#1]
Dear

I just tested it with example files provided.
But it did not work at the very last step with the error message as seen below. Please let me know.

> corrplot_nsquare(rg, traitlist1$TRAIT, traitlist2$TRAIT, landscape=TRUE)
Error in match.arg(method) : 
  'arg' should be one of “circle”, “square”, “ellipse”, “number”, “shade”, “color”, “pie”

**Comment by DoYup** [comment]
I guess there might be one thing in which method = "psquare" may not be compatible.

corrplot(mat2, method = "psquare", order = order,
           p.mat = qmat2, sig.level = 0.05, sig = "pch",
           pch = "*", pch.cex = 1.5, full_col=FALSE,
           na.label = "square", na.label.col = "grey30")

**Comment by mkanai** [comment]
Yes, it's because I implemented `psquare` by modifying the original `corrplot` package. Please install the modified version of `corrplot` as instructed in README.

```
devtools::install_github("mkanai/corrplot")
```

Best,
Masa

**Comment by DoYup** [comment]
Thank U very much.

Sincerely,
Do Yup

sent from my Galaxy
