### ISSUE TITLE
FDR

### ISSUE THREAD

**Issue by Kai6662** [mkanai/ldsc-corrplot-rg#2]
Hi,
If I don't have FDR can I still draw the plot using this tool? Thank you.
Best,
Kai

**Comment by mkanai** [comment]
Hi Kai,

Yes, you can copy p-values to the q value column. You might want to set an appropriate significance threshold here:
https://github.com/mkanai/ldsc-corrplot-rg/blob/master/plot_corrplot_rg.R#L76

Best,
Masa
