### ISSUE TITLE
Error with code "Rscript plot_corrplot_rg.R input_rg.txt traitlist.txt"

### ISSUE THREAD

**Issue by sandiassaf** [mkanai/ldsc-corrplot-rg#3]
Can someone help resolve the issue, I input the above code in R and got the following error:

> Rscript plot_corrplot_rg.R input_rg.txt traitlist.txt
Error: unexpected symbol in "Rscript plot_corrplot_rg.R"

**Comment by mkanai** [comment]
Hi, would you mind sharing more details about your environment, R version (`sessionInfo()`), error message, etc?

In my environment, the following command works without any errors.
```
Rscript plot_corrplot_rg.R input_example/input_rg.txt input_example/traitlist.txt
```

Thanks!

**Comment by sandiassaf** [comment]
Hello, I set the working directory to a folder (named pw) on my desktop with input_rg.txt and traitlist.txt inside. I read the txt files through R and ran the above command.

**Comment by mkanai** [comment]
I see. Please run `Rscript` on your terminal, not inside the R interactive shell. You can find more documents on the web, e.g., https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/Rscript

Thanks!
